const PROJECT_URL='https://tqzmggopevyzxgxijgzi.supabase.co';
const KEY='sb_publishable_uUlMuJ7qEFXBKWBCeTju8A_f4aSzesa';
const APP_VERSION='san-juan-conecta-movil-v1.0-pilot';
const $=id=>document.getElementById(id);
const LS_PREFIX='sjc_mobile_v10_';
const state={
 access:localStorage.getItem(LS_PREFIX+'access')||'',
 refresh:localStorage.getItem(LS_PREFIX+'refresh')||'',
 expires:Number(localStorage.getItem(LS_PREFIX+'expires')||0),
 operator:null,modules:{},deviceOk:false,stream:null,scanning:false,detector:null,engine:'none',
 db:null,busySync:false,lastScan:'',lastScanAt:0,round:null,roster:[],selectedMovementStudent:null,lastSync:null
};

function toast(msg,ms=2600){const x=$('toast');x.textContent=msg;x.hidden=false;clearTimeout(x._t);x._t=setTimeout(()=>x.hidden=true,ms)}
function uuid(){return crypto.randomUUID?crypto.randomUUID():'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,c=>{const r=Math.random()*16|0,v=c==='x'?r:(r&3|8);return v.toString(16)})}
function nowIso(){return new Date().toISOString()}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function saveTokens(){localStorage.setItem(LS_PREFIX+'access',state.access||'');localStorage.setItem(LS_PREFIX+'refresh',state.refresh||'');localStorage.setItem(LS_PREFIX+'expires',String(state.expires||0))}
function clearTokens(){['access','refresh','expires'].forEach(k=>localStorage.removeItem(LS_PREFIX+k));state.access='';state.refresh='';state.expires=0}
async function parse(r){const t=await r.text();let d;try{d=JSON.parse(t)}catch{d={raw:t}}if(!r.ok)throw new Error(d.message||d.msg||d.error_description||d.error||('HTTP '+r.status));return d}
async function refreshIfNeeded(){
 if(state.access&&Date.now()<state.expires-60000)return true;
 if(!state.refresh)return false;
 try{const d=await parse(await fetch(PROJECT_URL+'/auth/v1/token?grant_type=refresh_token',{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:state.refresh})}));state.access=d.access_token;state.refresh=d.refresh_token;state.expires=Date.now()+((d.expires_in||3600)*1000);saveTokens();return true}catch(e){clearTokens();return false}
}
async function rpc(name,body={}){if(!(await refreshIfNeeded()))throw new Error('SESIÓN_REQUERIDA');return parse(await fetch(PROJECT_URL+'/rest/v1/rpc/'+name,{method:'POST',headers:{apikey:KEY,Authorization:'Bearer '+state.access,'Content-Type':'application/json'},body:JSON.stringify(body)}))}

function showLogin(){ $('loginView').classList.add('active');$('appView').classList.remove('active');$('bottomNav').hidden=true }
function showApp(){ $('loginView').classList.remove('active');$('appView').classList.add('active');$('bottomNav').hidden=false;go('home') }
function go(name){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));const target=$('screen'+name[0].toUpperCase()+name.slice(1));if(target)target.classList.add('active');document.querySelectorAll('[data-go]').forEach(b=>b.classList.toggle('active',b.dataset.go===name));if(name==='sync')renderQueue();if(name==='rounds')loadRoundContext();}
document.addEventListener('click',e=>{const b=e.target.closest('[data-go]');if(b)go(b.dataset.go)});

async function login(){
 const email=$('email').value.trim(),password=$('password').value;if(!email||!password)return toast('Ingrese correo y contraseña.');
 $('loginBtn').disabled=true;
 try{const d=await parse(await fetch(PROJECT_URL+'/auth/v1/token?grant_type=password',{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify({email,password})}));state.access=d.access_token;state.refresh=d.refresh_token;state.expires=Date.now()+((d.expires_in||3600)*1000);saveTokens();$('password').value='';if(await loadContext()){showApp();await ensureDeviceCode();await loadModules();await verifyDevice(false);toast('Sesión iniciada.')}}catch(e){toast('No se pudo ingresar: '+e.message,4500)}finally{$('loginBtn').disabled=false}
}
$('loginBtn').onclick=login;
$('password').addEventListener('keydown',e=>{if(e.key==='Enter')login()});
$('logoutBtn').onclick=()=>{stopCamera();clearTokens();state.operator=null;state.deviceOk=false;showLogin();toast('Sesión cerrada')};

async function loadContext(){
 try{const r=await rpc('attendance_my_context');if(!r.authorized)throw new Error(r.reason||'OPERADOR_NO_ACTIVO');state.operator=r;$('operatorName').textContent=r.display_name||'Operador';$('operatorRole').textContent=roleLabel(r.operator_role);$('authPill').textContent='SESIÓN ACTIVA';$('authPill').className='pill ok';return true}catch(e){toast('Cuenta sin acceso móvil de asistencia: '+e.message,5000);showLogin();return false}
}
function roleLabel(r){return ({administrator:'Administrador',reconciler:'Coordinación / reconciliación',tutor:'Tutor',education_assistant:'Auxiliar',norms_discipline:'Normas y Disciplina',movement_area:'Área de movimiento'})[r]||r||'—'}
async function loadModules(){try{const r=await rpc('attendance_my_modules');state.modules={};(r.modules||[]).forEach(m=>state.modules[m.code]=!!m.allowed);$('modulesList').innerHTML=(r.modules||[]).map(m=>`<span class="chip ${m.allowed?'':'off'}">${esc(m.name)}</span>`).join('');applyModuleVisibility()}catch(e){$('modulesList').innerHTML='<span class="chip off">No se pudo cargar permisos</span>'}}
function applyModuleVisibility(){document.querySelectorAll('[data-go="reader"]').forEach(x=>x.hidden=state.modules.reader===false);document.querySelectorAll('[data-go="rounds"]').forEach(x=>x.hidden=state.modules.rounds===false);document.querySelectorAll('[data-go="movements"]').forEach(x=>x.hidden=state.modules.movements===false)}
$('refreshModulesBtn').onclick=loadModules;

function makeDeviceCode(){const a=new Uint8Array(4);crypto.getRandomValues(a);return 'SJB-MOVIL-'+[...a].map(x=>x.toString(16).padStart(2,'0')).join('').toUpperCase()}
async function ensureDeviceCode(){let code=localStorage.getItem(LS_PREFIX+'device_code');if(!code){code=makeDeviceCode();localStorage.setItem(LS_PREFIX+'device_code',code)}$('deviceCode').value=code}
$('deviceCode').addEventListener('change',()=>localStorage.setItem(LS_PREFIX+'device_code',$('deviceCode').value.trim()));
async function verifyDevice(showMessage=true){
 try{const code=$('deviceCode').value.trim();if(!code)throw new Error('FALTA_CÓDIGO');localStorage.setItem(LS_PREFIX+'device_code',code);const r=await rpc('attendance_device_status',{p_device_code:code});if(!r.authorized)throw new Error(r.reason||'NO_AUTORIZADO');state.deviceOk=true;$('devicePill').textContent='DISPOSITIVO OK';$('devicePill').className='pill ok';if(showMessage)toast('Dispositivo autorizado');heartbeat();return true}catch(e){state.deviceOk=false;$('devicePill').textContent='NO AUTORIZADO';$('devicePill').className='pill warn';if(showMessage)toast('Dispositivo pendiente: '+e.message,4000);return false}
}
$('verifyDeviceBtn').onclick=()=>verifyDevice(true);

async function openDb(){if(state.db)return state.db;state.db=await new Promise((resolve,reject)=>{const q=indexedDB.open('sjc_mobile_v10',1);q.onupgradeneeded=()=>{const db=q.result;if(!db.objectStoreNames.contains('qr_queue'))db.createObjectStore('qr_queue',{keyPath:'client_event_id'})};q.onsuccess=()=>resolve(q.result);q.onerror=()=>reject(q.error)});return state.db}
async function qAll(){const db=await openDb();return new Promise((res,rej)=>{const r=db.transaction('qr_queue').objectStore('qr_queue').getAll();r.onsuccess=()=>res(r.result||[]);r.onerror=()=>rej(r.error)})}
async function qPut(row){const db=await openDb();return new Promise((res,rej)=>{const tx=db.transaction('qr_queue','readwrite');tx.objectStore('qr_queue').put(row);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)})}
async function qDelete(id){const db=await openDb();return new Promise((res,rej)=>{const tx=db.transaction('qr_queue','readwrite');tx.objectStore('qr_queue').delete(id);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)})}
async function updateQueueUI(){const q=await qAll();$('queuePill').textContent='COLA '+q.length;$('pendingCount').textContent=q.length;return q}

async function heartbeat(){try{if(!state.deviceOk||!state.operator)return;const q=await qAll();await rpc('attendance_device_heartbeat',{p_device_code:$('deviceCode').value.trim(),p_pending_local_count:q.length,p_connection_state:navigator.onLine?(state.busySync?'syncing':'online'):'offline',p_app_version:APP_VERSION,p_platform:navigator.userAgent.slice(0,180)})}catch(e){}}
setInterval(heartbeat,30000);

async function captureToken(token,source='camera'){
 token=(token||'').trim();if(!token)return;const now=Date.now();if(token===state.lastScan&&now-state.lastScanAt<3000)return;state.lastScan=token;state.lastScanAt=now;
 if(!state.deviceOk&&!(await verifyDevice(true)))return;
 const row={client_event_id:uuid(),qr_token:token,device_code:$('deviceCode').value.trim(),captured_at:nowIso(),source};await qPut(row);setScanResult('CAPTURADO · guardado en el teléfono','warn');await updateQueueUI();syncQueue();
}
function setScanResult(msg,cls=''){$('scanResult').textContent=msg;$('scanResult').className='result-card '+cls}
async function syncQueue(){
 if(state.busySync||!navigator.onLine||!state.deviceOk)return;state.busySync=true;$('syncPill').textContent='SINCRONIZANDO';
 try{const rows=await qAll();for(const row of rows){try{const r=await rpc('attendance_ingest_scan',{p_client_event_id:row.client_event_id,p_qr_token:row.qr_token,p_device_code:row.device_code,p_captured_at:row.captured_at});await qDelete(row.client_event_id);const late=r.punctuality_classification==='late'?' · TARDANZA':'';const cross=r.cross_section_scan?' · OTRA AULA':'';setScanResult((r.duplicate_attendance?'YA REGISTRADO':'REGISTRADO')+' · '+(r.student_name||'')+' · '+(r.section_name||'')+late+cross,'ok');state.lastSync=new Date()}catch(e){const m=e.message||'';if(/QR_INVALID|STUDENT_NOT_ACTIVE|ACTIVE_ENROLLMENT_NOT_FOUND|CAPTURE_TIME_OUT_OF_RANGE|INVALID_INPUT/.test(m)){await qDelete(row.client_event_id);setScanResult('RECHAZADO · '+m,'bad')}else break}}}
 finally{state.busySync=false;await updateQueueUI();$('syncPill').textContent=(await qAll()).length?'PENDIENTE':'SINCRONIZADO';renderQueue();heartbeat()}
}

async function chooseEngine(){if('BarcodeDetector'in window){try{const f=await BarcodeDetector.getSupportedFormats();if(f.includes('qr_code')){state.detector=new BarcodeDetector({formats:['qr_code']});state.engine='native';$('enginePill').textContent='QR NATIVO';$('enginePill').className='pill ok';return}}catch(e){}}if(await loadJsQr()){state.engine='jsqr';$('enginePill').textContent='QR jsQR';$('enginePill').className='pill ok';return}state.engine='none';$('enginePill').textContent='SIN MOTOR';$('enginePill').className='pill bad'}
async function loadJsQr(){if(window.jsQR)return true;return new Promise(resolve=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/jsqr@1.4.0/dist/jsQR.min.js';s.onload=()=>resolve(true);s.onerror=()=>resolve(false);document.head.appendChild(s)})}
async function startCamera(){try{if(!state.deviceOk&&!(await verifyDevice(true)))return;if(!navigator.mediaDevices?.getUserMedia)throw new Error('CÁMARA_NO_DISPONIBLE');await chooseEngine();if(state.engine==='none')throw new Error('SIN_MOTOR_QR');state.stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});$('video').srcObject=state.stream;await $('video').play();state.scanning=true;$('cameraPill').textContent='ACTIVA';$('cameraPill').className='pill ok';$('cameraNote').textContent='Escaneo continuo activo.';const canvas=$('canvas'),ctx=canvas.getContext('2d',{willReadFrequently:true});const loop=async()=>{if(!state.scanning)return;try{if(state.engine==='native'){const codes=await state.detector.detect($('video'));if(codes?.[0]?.rawValue)await captureToken(codes[0].rawValue,'camera')}else if($('video').videoWidth){const w=Math.min($('video').videoWidth,720),h=Math.round($('video').videoHeight*w/$('video').videoWidth);canvas.width=w;canvas.height=h;ctx.drawImage($('video'),0,0,w,h);const im=ctx.getImageData(0,0,w,h);const q=jsQR(im.data,w,h,{inversionAttempts:'attemptBoth'});if(q?.data)await captureToken(q.data,'camera')}}catch(e){}setTimeout(loop,state.engine==='native'?120:180)};loop()}catch(e){$('cameraPill').textContent='ERROR';$('cameraPill').className='pill bad';$('cameraNote').textContent='No se pudo abrir cámara: '+e.message}}
function stopCamera(){state.scanning=false;if(state.stream)state.stream.getTracks().forEach(t=>t.stop());state.stream=null;$('video').srcObject=null;if($('cameraPill')){$('cameraPill').textContent='DETENIDA';$('cameraPill').className='pill'}}
$('startCameraBtn').onclick=startCamera;$('stopCameraBtn').onclick=stopCamera;$('manualCaptureBtn').onclick=()=>{const v=$('manualToken').value;$('manualToken').value='';captureToken(v,'manual')};

async function loadRoundContext(){if(!state.operator||state.modules.rounds===false)return;try{const r=await rpc('attendance_round_context');const sel=$('roundSection');sel.innerHTML='<option value="">Seleccione aula</option>'+(r.sections||[]).map(s=>`<option value="${s.section_id}">${esc(s.level_name)} · ${esc(s.grade_name)} ${esc(s.section_name)} · ${esc(s.campus_name)} (${s.expected_count})</option>`).join('')}catch(e){toast('No se pudo cargar aulas: '+e.message)}}
$('loadRosterBtn').onclick=loadRoster;
async function loadRoster(){const id=$('roundSection').value;if(!id)return toast('Seleccione un aula.');try{const r=await rpc('attendance_round_roster',{p_section_id:id});state.roster=(r.students||[]).map(s=>({...s,uiState:'in_class',exceptionId:null,note:''}));state.round=null;$('roundMeta').textContent=`${r.level_name||''} · ${r.grade_name||''} ${r.section_name||''} · ${r.campus_name||''} · ${r.expected_count||0} estudiantes`;renderRoster()}catch(e){toast('No se pudo cargar ronda: '+e.message)}}
$('startRoundBtn').onclick=async()=>{const section=$('roundSection').value;if(!section)return toast('Seleccione y cargue un aula.');if(!state.roster.length)await loadRoster();try{const r=await rpc('attendance_start_round',{p_client_round_id:uuid(),p_section_id:section,p_started_at:nowIso()});state.round={id:r.round_id};toast('Ronda iniciada. Todos quedan En aula por defecto.')}catch(e){toast('No se pudo iniciar: '+e.message,4000)}};
function renderRoster(){$('roundRoster').innerHTML=state.roster.map((s,i)=>`<div class="student-row ${s.uiState==='in_class'?'':'exception'}" data-i="${i}"><div class="student-top"><div><div class="student-name">${esc(s.name)}</div><div class="student-meta">Asistencia: ${esc(s.attendance_status||'sin marcación')}${s.destination?' · '+esc(s.destination):''}</div></div><button class="student-state" data-student-state="${i}">${stateLabel(s.uiState)}</button></div><div class="student-controls"><select data-state-select="${i}"><option value="in_class" ${s.uiState==='in_class'?'selected':''}>En aula</option><option value="other_area" ${s.uiState==='other_area'?'selected':''}>Otra área / justificado</option><option value="verify" ${s.uiState==='verify'?'selected':''}>En verificación</option><option value="absent" ${s.uiState==='absent'?'selected':''}>No ubicado / posible ausencia</option></select><label>Observación</label><div class="voice-row"><textarea data-note="${i}" rows="2" placeholder="Escribe o dicta">${esc(s.note||'')}</textarea><button class="mic" data-voice-index="${i}">🎙</button></div><button class="soft wide" data-save-exception="${i}">Guardar excepción</button></div></div>`).join('')}
function stateLabel(s){return ({in_class:'EN AULA',other_area:'OTRA ÁREA',verify:'VERIFICAR',absent:'NO UBICADO'})[s]||s}
document.addEventListener('click',async e=>{let i;if(e.target.matches('[data-student-state]')){i=Number(e.target.dataset.studentState);state.roster[i].uiState=state.roster[i].uiState==='in_class'?'verify':'in_class';renderRoster()}if(e.target.matches('[data-save-exception]')){i=Number(e.target.dataset.saveException);await saveRoundException(i)}if(e.target.matches('[data-voice-index]')){i=Number(e.target.dataset.voiceIndex);const ta=document.querySelector(`[data-note="${i}"]`);dictateTo(ta)}});
document.addEventListener('change',e=>{if(e.target.matches('[data-state-select]')){const i=Number(e.target.dataset.stateSelect);state.roster[i].uiState=e.target.value;renderRoster()}});
document.addEventListener('input',e=>{if(e.target.matches('[data-note]'))state.roster[Number(e.target.dataset.note)].note=e.target.value});
async function saveRoundException(i){if(!state.round?.id)return toast('Primero inicia la ronda.');const s=state.roster[i];s.note=(document.querySelector(`[data-note="${i}"]`)?.value||s.note||'').trim();if(s.uiState==='in_class'){if(s.exceptionId){try{await rpc('attendance_resolve_round_exception',{p_exception_id:s.exceptionId,p_resolution_type:'returned_to_class',p_note:s.note});s.exceptionId=null;toast('Marcado nuevamente En aula')}catch(e){toast(e.message)}}return}const map={other_area:'justified_out',verify:'requires_verification',absent:'not_located'};try{const r=await rpc('attendance_round_exception',{p_round_id:state.round.id,p_student_id:s.student_id,p_exception_type:map[s.uiState],p_note:s.note||null});s.exceptionId=r.exception_id;toast(r.auto_resolved?'Excepción registrada y justificada por movimiento':'Excepción registrada')}catch(e){toast('No se pudo guardar: '+e.message,4000)}}
$('closeRoundBtn').onclick=async()=>{if(!state.round?.id)return toast('No hay una ronda iniciada.');try{const r=await rpc('attendance_close_round',{p_round_id:state.round.id});if(r.ok){toast('Ronda cerrada correctamente');state.round=null}else toast(`Faltan ${r.unresolved_count||0} excepciones por resolver`,4500)}catch(e){toast('No se pudo cerrar: '+e.message,4500)}};

let searchTimer=null;$('movementSearch').addEventListener('input',()=>{clearTimeout(searchTimer);const q=$('movementSearch').value.trim();if(q.length<2){$('movementResults').innerHTML='';return}searchTimer=setTimeout(()=>searchMovement(q),240)});
async function searchMovement(q){try{const r=await rpc('attendance_movement_search_students',{p_query:q,p_limit:20});$('movementResults').innerHTML=(r.students||[]).map((s,i)=>`<button class="search-item" data-move-student="${i}"><b>${esc(s.name)}</b><small>${esc(s.level_name)} · ${esc(s.grade_name)} ${esc(s.section_name)} · ${esc(s.campus_name)}${s.active_movement_id?' · MOVIMIENTO ACTIVO':''}</small></button>`).join('')||'<p class="hint">Sin coincidencias.</p>';$('movementResults')._rows=r.students||[]}catch(e){toast('Búsqueda: '+e.message)}}
document.addEventListener('click',e=>{const b=e.target.closest('[data-move-student]');if(b){const s=$('movementResults')._rows?.[Number(b.dataset.moveStudent)];if(s)selectMovementStudent(s)}});
function selectMovementStudent(s){state.selectedMovementStudent=s;$('movementForm').hidden=false;$('movementStudentName').textContent=s.name;$('movementStudentMeta').textContent=`${s.level_name||''} · ${s.grade_name||''} ${s.section_name||''} · ${s.campus_name||''}`;$('movementResults').innerHTML='';$('movementSearch').value=s.name;if(s.active_movement_id){$('activeMovementBox').hidden=false;$('activeMovementBox').innerHTML=`<b>Movimiento activo</b><br>${esc(s.active_movement_type||'')} · ${esc(s.active_destination||'')}<br><small>Salida: ${fmtDateTime(s.active_started_at)}</small>`;$('newMovementFields').hidden=true;$('endMovementBtn').hidden=false}else{$('activeMovementBox').hidden=true;$('newMovementFields').hidden=false;$('endMovementBtn').hidden=true}}
$('registerMovementBtn').onclick=async()=>{const s=state.selectedMovementStudent;if(!s)return toast('Seleccione estudiante.');const type=$('movementType').value,dest=$('movementDestination').value.trim(),resp=$('movementResponsible').value.trim(),note=$('movementNote').value.trim();const destination=[dest,resp?('Responsable: '+resp):''].filter(Boolean).join(' · ');try{await rpc('attendance_register_movement',{p_client_event_id:uuid(),p_student_id:s.student_id,p_movement_type:type,p_destination:destination||null,p_reason:note||null,p_started_at:nowIso()});toast('Salida registrada');searchMovement(s.name)}catch(e){toast('No se pudo registrar: '+e.message,4500)}};
$('endMovementBtn').onclick=async()=>{const s=state.selectedMovementStudent;if(!s)return;try{await rpc('attendance_end_movement',{p_student_id:s.student_id,p_ended_at:nowIso()});toast('Retorno registrado');state.selectedMovementStudent=null;$('movementForm').hidden=true;$('movementSearch').value='';}catch(e){toast('No se pudo registrar retorno: '+e.message,4500)}};

function dictateTo(el){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR)return toast('Este navegador no ofrece dictado de voz. Prueba Chrome actualizado.');const r=new SR();r.lang='es-PE';r.interimResults=false;r.maxAlternatives=1;r.onstart=()=>toast('Escuchando…');r.onerror=e=>toast('Micrófono: '+e.error);r.onresult=e=>{const t=e.results[0][0].transcript.trim();el.value=(el.value?el.value.trim()+' ':'')+t;el.dispatchEvent(new Event('input',{bubbles:true}));toast('Texto dictado')};r.start()}
document.addEventListener('click',e=>{const b=e.target.closest('[data-voice]');if(b)dictateTo($(b.dataset.voice))});

async function renderQueue(){const q=await updateQueueUI();$('connectionText').textContent=navigator.onLine?'ONLINE':'OFFLINE';$('lastSyncText').textContent=state.lastSync?state.lastSync.toLocaleTimeString('es-PE',{hour:'2-digit',minute:'2-digit'}):'—';$('queueList').innerHTML=q.map(x=>`<div class="queue-item"><b>${esc(x.source||'QR')}</b><br><small>${esc(x.client_event_id)} · ${fmtDateTime(x.captured_at)}</small></div>`).join('')||'<div class="card hint">No hay eventos pendientes.</div>'}
$('syncNowBtn').onclick=async()=>{if(!state.deviceOk)await verifyDevice(true);await syncQueue();toast('Sincronización revisada')};
$('exportQueueBtn').onclick=async()=>{const q=await qAll();const blob=new Blob([JSON.stringify({app:APP_VERSION,exported_at:nowIso(),device_code:$('deviceCode').value,queue:q},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='SJC_MOVIL_CONTINGENCIA_'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
function fmtDateTime(v){if(!v)return'—';try{return new Date(v).toLocaleString('es-PE',{dateStyle:'short',timeStyle:'short'})}catch{return v}}
function updateNet(){$('netPill').textContent=navigator.onLine?'ONLINE':'OFFLINE';$('netPill').className='pill '+(navigator.onLine?'ok':'warn');if(navigator.onLine)syncQueue();renderQueue()}window.addEventListener('online',updateNet);window.addEventListener('offline',updateNet);

async function boot(){updateNet();await ensureDeviceCode();await updateQueueUI();chooseEngine();if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('./sw.js').catch(()=>{});if(state.access&&await refreshIfNeeded()&&await loadContext()){showApp();await loadModules();await verifyDevice(false)}else showLogin()}
boot();
